library(data.table)
library(arrow)
library(argparse)
library(lubridate)
library(lgr)

source("R/constantes.r")
source("R/logging.r")
source("R/utils.r")
source("R/parser.r")
source("R/validacao.r")
source("R/leitura.r")
source("R/consistencia-dados.r")
source("R/preenchimento-dados-faltantes.r")
